name: Manage EC2 Instance

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'start or stop'
        required: true
        default: 'start'

jobs:
  manage-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EC2_REGION }}

      - name: Start EC2 Instance
        if: ${{ github.event.inputs.action == 'start' }}
        run: |
          aws ec2 start-instances --instance-ids ${{ secrets.EC2_ID }}

      - name: Stop EC2 Instance
        if: ${{ github.event.inputs.action == 'stop' }}
        run: |
          aws ec2 stop-instances --instance-ids ${{ secrets.EC2_ID }}
